## 인덱싱 - 미니퀘스트


### 1번 퀘스트

1차원 배열 [10, 20, 30, 40, 50]에서
첫 번째 요소와 마지막 요소를 출력하는 코드를 작성하세요.


In [ ]:
import numpy as np

array = np.array([10,20,30,40,50])
print(array[0])
print(array[4])

### 2번 퀘스트

2차원 배열에서 첫 번째 열과 두 번째 행을 출력하는 코드를 작성하세요.


In [3]:
import numpy as np
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print(matrix[:, 0])
print(matrix[1])

[1 4 7]
[4 5 6]


### 3번 퀘스트

배열 [5, 15, 8, 20, 3, 12]에서
10보다 큰 요소들만 선택하고, 해당 요소들의 인덱스를 출력하는 코드를 작성하세요.


In [28]:
import numpy as np
array = np.array([5, 15, 8, 20, 3, 12])

print(array[array > 10])
print(np.where(array > 10) [0].tolist())

[15 20 12]
[1, 3, 5]
